import 'dart:io';
/*NOMES : DANIEL GUIMARÃES E MARCOS AURÉLIO
TURMA: 2° INFORMÁTICA VESPERTINO*/

void main(){
  print("NOMES : DANIEL GUIMARÃES E MARCOS AURÉLIO\nTURMA: 2° INFORMÁTICA VESPERTINO");

}

